# Extend from quay.io/podman/stable
FROM quay.io/podman/stable

ARG JENKINS_AGENT_WORKDIR
ARG JENKINS_URL
ARG JENKINS_AGENT_NAME
ARG JENKINS_SECRET

WORKDIR ${JENKINS_AGENT_WORKDIR}

RUN dnf install -y java-21-openjdk-devel wget \
    && dnf clean all

RUN wget ${JENKINS_URL}jnlpJars/agent.jar -O /tmp/agent.jar

ENTRYPOINT java -jar /tmp/agent.jar \
    -jnlpUrl ${JENKINS_URL}computer/${JENKINS_AGENT_NAME}/jenkins-agent.jnlp \
    -secret ${JENKINS_SECRET}
