# Extend from quay.io/podman/stable
FROM quay.io/podman/stable

RUN rpm --import https://yum.corretto.aws/corretto.key \
    && curl -Lo /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo \
    && dnf install -y java-21-amazon-corretto-devel wget \
    && dnf clean all

USER podman

ARG JENKINS_AGENT_WORKDIR
ARG JENKINS_URL
ARG JENKINS_AGENT_NAME
ARG JENKINS_SECRET

ENV JENKINS_AGENT_WORKDIR=${JENKINS_AGENT_WORKDIR}
ENV JENKINS_SECRET=${JENKINS_SECRET}
ENV JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
ENV JENKINS_URL=${JENKINS_URL}

WORKDIR ${JENKINS_AGENT_WORKDIR}

RUN wget ${JENKINS_URL}jnlpJars/agent.jar -O /tmp/agent.jar

CMD java -jar /tmp/agent.jar \
    -url $JENKINS_URL -name $JENKINS_AGENT_NAME -secret $JENKINS_SECRET -webSocket -workDir $JENKINS_AGENT_WORKDIR
